// <auto-generated />
using BlazorFullStackCrudCustom.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorFullStackCrudCustom.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorFullStackCrudCustom.Shared.Appilcation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Appilcations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Smart Care"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "IT Asset Manager"
                        });
                });

            modelBuilder.Entity("BlazorFullStackCrudCustom.Shared.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AppilcationId")
                        .HasColumnType("int");

                    b.Property<string>("AppilcationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppilcationId");

                    b.HasIndex("VoteId");

                    b.ToTable("FeedBackes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppilcationId = 1,
                            AppilcationName = "Smart Care",
                            Description = "Error 404",
                            VoteId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppilcationId = 2,
                            AppilcationName = "Chat Bot",
                            Description = "Error 405",
                            VoteId = 2
                        });
                });

            modelBuilder.Entity("BlazorFullStackCrudCustom.Shared.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Votes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "5"
                        });
                });

            modelBuilder.Entity("BlazorFullStackCrudCustom.Shared.FeedBack", b =>
                {
                    b.HasOne("BlazorFullStackCrudCustom.Shared.Appilcation", "Appilcation")
                        .WithMany()
                        .HasForeignKey("AppilcationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorFullStackCrudCustom.Shared.Vote", "Vote")
                        .WithMany()
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appilcation");

                    b.Navigation("Vote");
                });
#pragma warning restore 612, 618
        }
    }
}
